### ISSUE TITLE
Typo in ServerMain class for Networking Part 1?

### ISSUE THREAD

**Issue by kuhlde1337** [Luaancz/Networking#1]
I realize it has been a few years since this was uploaded, but in case you are still watching this repo, I had a question about the following line of code from ServerMain.Access in the Networking Part 1 solution:

`
 // If ReadAsync returns zero, it means the connection was closed from the other side. If it doesn't, 
 //we have to close it ourselves. `
`
if (bytesRead != 0) client.Close(); // Do a graceful shutdown
`

If I'm following this right shouldn't we be checking if bytesRead is equal to 0 instead of not equal? If not, would you mind explaining that to me?

**Comment by Luaancz** [comment]
No - though in this example, it doesn't make a difference either way.

The idea in the loop is to keep reading until we read all the bytes we're expecting (as per the header already received). However, if the client disconnects before the loop finishes, `ReadAsync` will return zero - that means the connection has been closed, and we didn't receive all the data we asked for. If the client _didn't_ disconnect, we need to close the connection ourselves, hence the `bytesRead != 0`. Though I have to say, I'm not sure if this approach could leave the socket in a half-closed state - it's been a while since I've played with TCP :)

**Comment by kuhlde1337** [comment]
I see. Thank you for the reply. I had actually found this repo from a post you had made on Stack Overflow a while back. There you said that many of the C# examples for TCP are flawed. I was wondering if you knew of any online resources I could use to learn TCP more in depth that teach it the correct way? Thanks again.
